debug: false
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:mem:sampledb
    username: u
    password: p
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: true
  output.ansi.enabled: always
management:
  Xendpoints:
    comment: To enable all actuator endpoints, 1) remove the leading X from the preceding line and 2) remove this line.
    web:
      exposure:
        include: "*"