debug: false
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/ohlis
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: true
  output.ansi.enabled: always
---
spring:
  config:
    activate:
      on-profile: local 
  datasource:
    url: jdbc:postgresql://localhost:5432/ohlis
---
spring:
  config:
    activate:
      on-profile: actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"